USE [PokerTracker]
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_Sessions_HoursActive')
ALTER TABLE [dbo].[Sessions] DROP CONSTRAINT [CK_Sessions_HoursActive]
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'PercentOfTimePlayed' AND TABLE_NAME = 'Sessions')
ALTER TABLE [dbo].[Sessions] ADD [PercentOfTimePlayed] INT NULL
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'HoursActive' AND TABLE_NAME = 'Sessions')
EXEC sp_executesql N'UPDATE [dbo].[Sessions]
SET [PercentOfTimePlayed] = CEILING([HoursActive] * 60 / DATEDIFF(minute, StartTime, EndTime) * 100)'
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'HoursActive')
ALTER TABLE [dbo].[Sessions]
DROP COLUMN [HoursActive]
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_Sessions_PercentOfTimePlayed')
ALTER TABLE [dbo].[Sessions]
ADD CONSTRAINT [CK_Sessions_PercentOfTimePlayed]
CHECK ([PercentOfTimePlayed] BETWEEN 0 AND 100)
GO